github: [bewcloud, BrunoBernardino]
custom:
  [
    'https://payment-links.mollie.com/payment/wUS9dvewvjEPvseZVHEi5',
    'https://paypal.me/brunobernardino',
    'https://paste.sr.ht/~brn/f3e7883f758c3a82caec1cd360bffb23941be3c7',
  ]
