github: [bewcloud, BrunoBernardino]
custom:
  [
    'https://payment-links.mollie.com/payment/wUS9dvewvjEPvseZVHEi5',
    'https://paypal.me/brunobernardino',
    'https://gist.github.com/BrunoBernardino/ff5b54c13dd96ac7f9fee6fbfd825b09',
  ]
