github: [bewcloud, BrunoBernardino]
custom:
  [
    'https://donate.stripe.com/bIYeWBbw00Ape5iaFi',
    'https://paypal.me/brunobernardino',
    'https://gist.github.com/BrunoBernardino/ff5b54c13dd96ac7f9fee6fbfd825b09',
  ]
