// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_well_known_caldav from './routes/.well-known/caldav.tsx';
import * as $_well_known_carddav from './routes/.well-known/carddav.tsx';
import * as $_404 from './routes/_404.tsx';
import * as $_app from './routes/_app.tsx';
import * as $_middleware from './routes/_middleware.tsx';
import * as $api_auth_multi_factor_disable from './routes/api/auth/multi-factor/disable.ts';
import * as $api_auth_multi_factor_email_setup from './routes/api/auth/multi-factor/email/setup.ts';
import * as $api_auth_multi_factor_enable from './routes/api/auth/multi-factor/enable.ts';
import * as $api_auth_multi_factor_passkey_begin from './routes/api/auth/multi-factor/passkey/begin.ts';
import * as $api_auth_multi_factor_passkey_setup_begin from './routes/api/auth/multi-factor/passkey/setup-begin.ts';
import * as $api_auth_multi_factor_passkey_setup_complete from './routes/api/auth/multi-factor/passkey/setup-complete.ts';
import * as $api_auth_multi_factor_passkey_verify from './routes/api/auth/multi-factor/passkey/verify.ts';
import * as $api_auth_multi_factor_totp_setup from './routes/api/auth/multi-factor/totp/setup.ts';
import * as $api_dashboard_save_links from './routes/api/dashboard/save-links.tsx';
import * as $api_dashboard_save_notes from './routes/api/dashboard/save-notes.tsx';
import * as $api_expenses_add_budget from './routes/api/expenses/add-budget.tsx';
import * as $api_expenses_add_expense from './routes/api/expenses/add-expense.tsx';
import * as $api_expenses_auto_complete from './routes/api/expenses/auto-complete.tsx';
import * as $api_expenses_delete_budget from './routes/api/expenses/delete-budget.tsx';
import * as $api_expenses_delete_expense from './routes/api/expenses/delete-expense.tsx';
import * as $api_expenses_export_expenses from './routes/api/expenses/export-expenses.tsx';
import * as $api_expenses_import_expenses from './routes/api/expenses/import-expenses.tsx';
import * as $api_expenses_update_budget from './routes/api/expenses/update-budget.tsx';
import * as $api_expenses_update_expense from './routes/api/expenses/update-expense.tsx';
import * as $api_files_create_directory from './routes/api/files/create-directory.tsx';
import * as $api_files_create_share from './routes/api/files/create-share.tsx';
import * as $api_files_delete_directory from './routes/api/files/delete-directory.tsx';
import * as $api_files_delete_share from './routes/api/files/delete-share.tsx';
import * as $api_files_delete from './routes/api/files/delete.tsx';
import * as $api_files_get_directories from './routes/api/files/get-directories.tsx';
import * as $api_files_get_share from './routes/api/files/get-share.tsx';
import * as $api_files_get from './routes/api/files/get.tsx';
import * as $api_files_move_directory from './routes/api/files/move-directory.tsx';
import * as $api_files_move from './routes/api/files/move.tsx';
import * as $api_files_rename_directory from './routes/api/files/rename-directory.tsx';
import * as $api_files_rename from './routes/api/files/rename.tsx';
import * as $api_files_search from './routes/api/files/search.tsx';
import * as $api_files_update_share from './routes/api/files/update-share.tsx';
import * as $api_files_upload from './routes/api/files/upload.tsx';
import * as $api_news_add_feed from './routes/api/news/add-feed.tsx';
import * as $api_news_delete_feed from './routes/api/news/delete-feed.tsx';
import * as $api_news_import_feeds from './routes/api/news/import-feeds.tsx';
import * as $api_news_mark_read from './routes/api/news/mark-read.tsx';
import * as $api_news_refresh_articles from './routes/api/news/refresh-articles.tsx';
import * as $api_notes_save from './routes/api/notes/save.tsx';
import * as $caldav from './routes/caldav.tsx';
import * as $carddav from './routes/carddav.tsx';
import * as $dashboard from './routes/dashboard.tsx';
import * as $dav from './routes/dav.tsx';
import * as $expenses from './routes/expenses.tsx';
import * as $file_share_fileShareId_ from './routes/file-share/[fileShareId].tsx';
import * as $file_share_fileShareId_open_fileName_ from './routes/file-share/[fileShareId]/open/[fileName].tsx';
import * as $file_share_fileShareId_verify from './routes/file-share/[fileShareId]/verify.tsx';
import * as $files from './routes/files.tsx';
import * as $files_open_fileName_ from './routes/files/open/[fileName].tsx';
import * as $index from './routes/index.tsx';
import * as $login from './routes/login.tsx';
import * as $logout from './routes/logout.tsx';
import * as $mfa_verify from './routes/mfa-verify.tsx';
import * as $news from './routes/news.tsx';
import * as $news_feeds from './routes/news/feeds.tsx';
import * as $notes from './routes/notes.tsx';
import * as $notes_open_fileName_ from './routes/notes/open/[fileName].tsx';
import * as $oidc_callback from './routes/oidc/callback.tsx';
import * as $photos from './routes/photos.tsx';
import * as $photos_thumbnail_fileName_ from './routes/photos/thumbnail/[fileName].tsx';
import * as $settings from './routes/settings.tsx';
import * as $signup from './routes/signup.tsx';
import * as $Settings from './islands/Settings.tsx';
import * as $auth_MultiFactorAuthSettings from './islands/auth/MultiFactorAuthSettings.tsx';
import * as $auth_PasswordlessPasskeyLogin from './islands/auth/PasswordlessPasskeyLogin.tsx';
import * as $dashboard_Links from './islands/dashboard/Links.tsx';
import * as $dashboard_Notes from './islands/dashboard/Notes.tsx';
import * as $expenses_ExpensesWrapper from './islands/expenses/ExpensesWrapper.tsx';
import * as $files_FilesWrapper from './islands/files/FilesWrapper.tsx';
import * as $news_Articles from './islands/news/Articles.tsx';
import * as $news_Feeds from './islands/news/Feeds.tsx';
import * as $notes_Note from './islands/notes/Note.tsx';
import * as $notes_NotesWrapper from './islands/notes/NotesWrapper.tsx';
import * as $photos_PhotosWrapper from './islands/photos/PhotosWrapper.tsx';
import type { Manifest } from '$fresh/server.ts';

const manifest = {
  routes: {
    './routes/.well-known/caldav.tsx': $_well_known_caldav,
    './routes/.well-known/carddav.tsx': $_well_known_carddav,
    './routes/_404.tsx': $_404,
    './routes/_app.tsx': $_app,
    './routes/_middleware.tsx': $_middleware,
    './routes/api/auth/multi-factor/disable.ts': $api_auth_multi_factor_disable,
    './routes/api/auth/multi-factor/email/setup.ts': $api_auth_multi_factor_email_setup,
    './routes/api/auth/multi-factor/enable.ts': $api_auth_multi_factor_enable,
    './routes/api/auth/multi-factor/passkey/begin.ts': $api_auth_multi_factor_passkey_begin,
    './routes/api/auth/multi-factor/passkey/setup-begin.ts': $api_auth_multi_factor_passkey_setup_begin,
    './routes/api/auth/multi-factor/passkey/setup-complete.ts': $api_auth_multi_factor_passkey_setup_complete,
    './routes/api/auth/multi-factor/passkey/verify.ts': $api_auth_multi_factor_passkey_verify,
    './routes/api/auth/multi-factor/totp/setup.ts': $api_auth_multi_factor_totp_setup,
    './routes/api/dashboard/save-links.tsx': $api_dashboard_save_links,
    './routes/api/dashboard/save-notes.tsx': $api_dashboard_save_notes,
    './routes/api/expenses/add-budget.tsx': $api_expenses_add_budget,
    './routes/api/expenses/add-expense.tsx': $api_expenses_add_expense,
    './routes/api/expenses/auto-complete.tsx': $api_expenses_auto_complete,
    './routes/api/expenses/delete-budget.tsx': $api_expenses_delete_budget,
    './routes/api/expenses/delete-expense.tsx': $api_expenses_delete_expense,
    './routes/api/expenses/export-expenses.tsx': $api_expenses_export_expenses,
    './routes/api/expenses/import-expenses.tsx': $api_expenses_import_expenses,
    './routes/api/expenses/update-budget.tsx': $api_expenses_update_budget,
    './routes/api/expenses/update-expense.tsx': $api_expenses_update_expense,
    './routes/api/files/create-directory.tsx': $api_files_create_directory,
    './routes/api/files/create-share.tsx': $api_files_create_share,
    './routes/api/files/delete-directory.tsx': $api_files_delete_directory,
    './routes/api/files/delete-share.tsx': $api_files_delete_share,
    './routes/api/files/delete.tsx': $api_files_delete,
    './routes/api/files/get-directories.tsx': $api_files_get_directories,
    './routes/api/files/get-share.tsx': $api_files_get_share,
    './routes/api/files/get.tsx': $api_files_get,
    './routes/api/files/move-directory.tsx': $api_files_move_directory,
    './routes/api/files/move.tsx': $api_files_move,
    './routes/api/files/rename-directory.tsx': $api_files_rename_directory,
    './routes/api/files/rename.tsx': $api_files_rename,
    './routes/api/files/search.tsx': $api_files_search,
    './routes/api/files/update-share.tsx': $api_files_update_share,
    './routes/api/files/upload.tsx': $api_files_upload,
    './routes/api/news/add-feed.tsx': $api_news_add_feed,
    './routes/api/news/delete-feed.tsx': $api_news_delete_feed,
    './routes/api/news/import-feeds.tsx': $api_news_import_feeds,
    './routes/api/news/mark-read.tsx': $api_news_mark_read,
    './routes/api/news/refresh-articles.tsx': $api_news_refresh_articles,
    './routes/api/notes/save.tsx': $api_notes_save,
    './routes/caldav.tsx': $caldav,
    './routes/carddav.tsx': $carddav,
    './routes/dashboard.tsx': $dashboard,
    './routes/dav.tsx': $dav,
    './routes/expenses.tsx': $expenses,
    './routes/file-share/[fileShareId].tsx': $file_share_fileShareId_,
    './routes/file-share/[fileShareId]/open/[fileName].tsx': $file_share_fileShareId_open_fileName_,
    './routes/file-share/[fileShareId]/verify.tsx': $file_share_fileShareId_verify,
    './routes/files.tsx': $files,
    './routes/files/open/[fileName].tsx': $files_open_fileName_,
    './routes/index.tsx': $index,
    './routes/login.tsx': $login,
    './routes/logout.tsx': $logout,
    './routes/mfa-verify.tsx': $mfa_verify,
    './routes/news.tsx': $news,
    './routes/news/feeds.tsx': $news_feeds,
    './routes/notes.tsx': $notes,
    './routes/notes/open/[fileName].tsx': $notes_open_fileName_,
    './routes/oidc/callback.tsx': $oidc_callback,
    './routes/photos.tsx': $photos,
    './routes/photos/thumbnail/[fileName].tsx': $photos_thumbnail_fileName_,
    './routes/settings.tsx': $settings,
    './routes/signup.tsx': $signup,
  },
  islands: {
    './islands/Settings.tsx': $Settings,
    './islands/auth/MultiFactorAuthSettings.tsx': $auth_MultiFactorAuthSettings,
    './islands/auth/PasswordlessPasskeyLogin.tsx': $auth_PasswordlessPasskeyLogin,
    './islands/dashboard/Links.tsx': $dashboard_Links,
    './islands/dashboard/Notes.tsx': $dashboard_Notes,
    './islands/expenses/ExpensesWrapper.tsx': $expenses_ExpensesWrapper,
    './islands/files/FilesWrapper.tsx': $files_FilesWrapper,
    './islands/news/Articles.tsx': $news_Articles,
    './islands/news/Feeds.tsx': $news_Feeds,
    './islands/notes/Note.tsx': $notes_Note,
    './islands/notes/NotesWrapper.tsx': $notes_NotesWrapper,
    './islands/photos/PhotosWrapper.tsx': $photos_PhotosWrapper,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
